import urllib.request
import time
outFile = open('log_test4.2.txt', 'w')

htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/16")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/17")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/18")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/19")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/20")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/21")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/22")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/23")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/24")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/25")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/26")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
outFile.close()
input("Pause for view text-------------------------------------------------")
