import urllib.request
import time
outFile = open('log_test4_.txt', 'w')

htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/2")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/3")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/4")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/5")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/6")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/7")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/8")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/9")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/10")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/11")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/12")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/13")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/14")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/15")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/16")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/17")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/18")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/19")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/20")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/21")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/22")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/23")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/24")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/25")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
htmlreq = urllib.request.urlopen("https://3dr.com/faa/drone-practice-tests/26")
htmltext = htmlreq.read()
outFile.write(str(htmltext,'utf-8'))
outFile.write("-----------------final---------------------------------------------------------------------")
print(str(htmltext,'utf-8'))
print("-------------------------final---------------------------------------------------------------------")
time.sleep(30)
outFile.close()
input("Pause for view text-------------------------------------------------")
