<?php

print "<!DOCTYPE html>\n";
print "\n";
print "<html>\n";
print "\n";
print "<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\" />\n";
print "\n";
print "<head>\n";
print "  <title>RedCat PropWare - Test Page</title>\n";
print "  <meta charset=\"utf-8\">\n";
print "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
print "  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n";
print "  <link rel=\"stylesheet\" href=\"assets/css/navbar-fixed-top.css\">\n";
print "  <link rel=\"stylesheet\" href=\"assets/css/main.css\">\n";
print "\n";
print "    <link rel=\"shortcut icon\" href=\"http://c.eqcdn.com/_b6d5425d7688a02ed6056ebd52866e98/redcatpropware/files/theme/images/favicons/favicon.ico\">\n";
print "    <link rel=\"icon\" type=\"image/png\" href=\"http://c.eqcdn.com/_b6d5425d7688a02ed6056ebd52866e98/redcatpropware/files/theme/images/favicons/favicon-16x16.png\" sizes=\"16x16\">\n";
print "    <link rel=\"icon\" type=\"image/png\" href=\"http://c.eqcdn.com/_b6d5425d7688a02ed6056ebd52866e98/redcatpropware/files/theme/images/favicons/favicon-32x32.png\" sizes=\"32x32\">\n";
print "    <link rel=\"apple-touch-icon\" href=\"http://c.eqcdn.com/_b6d5425d7688a02ed6056ebd52866e98/redcatpropware/files/theme/images/favicons/apple-touch-icon-precomposed.png\">\n";
print "    <link rel=\"apple-touch-icon\" href=\"http://c.eqcdn.com/_b6d5425d7688a02ed6056ebd52866e98/redcatpropware/files/theme/images/favicons/apple-touch-icon.png\">\n";
print "    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"http://c.eqcdn.com/_b6d5425d7688a02ed6056ebd52866e98/redcatpropware/files/theme/images/favicons/apple-touch-icon-57x57.png\">\n";
print "    <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"http://c.eqcdn.com/_b6d5425d7688a02ed6056ebd52866e98/redcatpropware/files/theme/images/favicons/apple-touch-icon-60x60.png\">\n";
print "    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"http://c.eqcdn.com/_b6d5425d7688a02ed6056ebd52866e98/redcatpropware/files/theme/images/favicons/apple-touch-icon-72x72.png\">\n";
print "    <link rel=\"icon\" type=\"image/png\" href=\"http://c.eqcdn.com/_b6d5425d7688a02ed6056ebd52866e98/redcatpropware/files/theme/images/favicons/android-chrome-36x36.png\" sizes=\"36x36\">\n";
print "    <link rel=\"icon\" type=\"image/png\" href=\"http://c.eqcdn.com/_b6d5425d7688a02ed6056ebd52866e98/redcatpropware/files/theme/images/favicons/android-chrome-48x48.png\" sizes=\"48x48\">\n";
print "    <link rel=\"icon\" type=\"image/png\" href=\"http://c.eqcdn.com/_b6d5425d7688a02ed6056ebd52866e98/redcatpropware/files/theme/images/favicons/android-chrome-72x72.png\" sizes=\"72x72\">\n";
print "    <link rel=\"mask-icon\" href=\"http://c.eqcdn.com/_b6d5425d7688a02ed6056ebd52866e98/redcatpropware/files/theme/images/favicons/safari-pinned-tab.svg\">\n";
print "    <meta name=\"msapplication-TileColor\" content=\"#ffffff\">\n";
print "    <meta name=\"msapplication-TileImage\" content=\"http://c.eqcdn.com/_b6d5425d7688a02ed6056ebd52866e98/redcatpropware/files/theme/images/favicons/mstile-70x70.png\">\n";
print "    <meta name=\"msapplication-TileImage\" content=\"http://c.eqcdn.com/_b6d5425d7688a02ed6056ebd52866e98/redcatpropware/files/theme/images/favicons/mstile-150x150.png\">\n";
print "    <meta name=\"msapplication-TileImage\" content=\"http://c.eqcdn.com/_b6d5425d7688a02ed6056ebd52866e98/redcatpropware/files/theme/images/favicons/mstile-310x150.png\">\n";
print "    <link rel=\"manifest\" href=\"http://c.eqcdn.com/_b6d5425d7688a02ed6056ebd52866e98/redcatpropware/files/theme/images/favicons/manifest.json\">\n";
print "    <meta name=\"msapplication-config\" content=\"http://c.eqcdn.com/_b6d5425d7688a02ed6056ebd52866e98/redcatpropware/files/theme/images/favicons/browserconfig.xml\">\n";
print "  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>\n";
print "  <script src=\"index.js\"></script>\n";
print "  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\n";
print "  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n";
print "  <style>\n";
print "    footer {\n";
print "      background-color: #f2f2f2;\n";
print "      padding: 25px;\n";
print "    }\n";
print "  </style>\n";
print "\n";
print "\n";
print "    <script src=\"assets/js/application-a7bf769176291065a4ee8792a676fa71d4bb6f33052800621dec777a09483815.js\" data-turbolinks-track=\"true\"></script>\n";
print "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
print "  </head>\n";
print "\n";
print "  <body id=\"faa_testing\" class=\"quiz\">\n";
print "\n";
print "    <nav class=\"navbar navbar-default navbar-fixed-top\">\n";
print "      <div class=\"container\">\n";
print "        <div class=\"navbar-header navbar-left\">\n";
print "          <a class=\"navbar-brand\" href=\"#\">\n";
print "            <span><img style=\"width: 45px;\" alt=\"Brand\" src=\"http://c.eqcdn.com/_b6d5425d7688a02ed6056ebd52866e98/redcatpropware/files/theme/images/header-logo@2x.png\"></span>\n";
print "            RedCat PropWare - Test Page\n";
print "          </a>\n";
print "        </div>\n";
print "        <div id=\"navbar\" class=\"navbar-collapse collapse navbar-right\">\n";
print "          <ul class=\"nav navbar-nav\">\n";
print "            <li><a href=\"http://many5694.github.io/index.html\">Home</a></li>\n";
print "            <li><a href=\"http://red-cat-hobbes.herokuapp.com/\">Log Up</a></li>\n";
print "            <li><a href=\"http://many5694.github.io/FAQs.html\">FAQs</a></li>\n";
print "            <li><a href=\"http://www.redcatpropware.com/about\">About</a></li>\n";
print "            <li><a href=\"http://red-cat-hobbes.herokuapp.com/\">Pricing</a></li>\n";
print "          </ul>\n";
print "        </div>\n";
print "      </div>\n";
print "    </nav>\n";
print "    \n";
print "\n";
print "      <!-- Magic Modal -->\n";
print "      <div class=\"modal fade\" id=\"faa_modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"FAA Quiz Modal\">\n";
print "        <div class=\"modal-dialog modal-lg\" role=\"document\">\n";
print "          <div class=\"modal-content\">\n";
print "            <div class=\"modal-header\">\n";
print "              <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">×</span></button>\n";
print "              <h4 class=\"modal-title\" id=\"faa_modal_title\"></h4>\n";
print "            </div>\n";
print "            <div class=\"modal-body\"></div>\n";
print "            <div class=\"modal-footer\">\n";
print "              <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n";
print "            </div>\n";
print "          </div>\n";
print "        </div>\n";
print "      </div>\n";
print "      <!-- End Magic Modal -->\n";
print "\n";
print "    \n";
print " <div class=\"container\">\n";
print "  <div class=\"row\">\n";
print "   <div class=\"col-sm-12\">\n";
print "   \n";
print "      <div class=\"panel panel-default\">\n";
print "\n";
print "        <div class=\"panel-heading\"><div class=\"container-fluid text-center\"><h1>Questions</h1><h2 class=\"status vanish\"></h2></div></div>\n";
print "        <div class=\"panel-body\">\n";
print "      <form id=\"faa_quiz\" data-questions=\"5\">\n";
print "           <ul id=\"posts\">\n";
print "          <div class=\"form-group question\">\n";
print "            <h3>What action should a remote-pilot take when operating in a Military Operations Area (MOA)?</h3>\n";
print "              <div class=\"radio\">\n";
print "                <label>\n";
print "                  <input type=\"radio\" name=\"question_0\" id=\"question_0_answer_0\" value=\"false\">\n";
print "                  Fly only along Military Training Routes (MTRs)\n";
print "                </label>\n";
print "              </div>\n";
print "              <div class=\"radio\">\n";
print "                <label>\n";
print "                  <input type=\"radio\" name=\"question_0\" id=\"question_0_answer_1\" value=\"false\">\n";
print "                  Obtain authorization from the controlling agency prior to operating in the MOA\n";
print "                </label>\n";
print "              </div>\n";
print "              <div class=\"radio\">\n";
print "                <label>\n";
print "                  <input type=\"radio\" name=\"question_0\" id=\"question_0_answer_2\" value=\"true\">\n";
print "                  Exercise extreme caution when military activity is being conducted\n";
print "                </label>\n";
print "              </div>\n";
print "          </div>\n";
print "          <hr>\n";
print "          <div class=\"form-group question\">\n";
print "            <h3>(Refer to figure 25, area 7.) The airspace overlying Mc Kinney airport (TKI) is controlled from the surface to</h3>\n";
print "              <ul class=\"nav nav-pills\">\n";
print "                  <li role=\"presentation\"><a href=\"#\" data-toggle=\"modal\" data-target=\"#faa_modal\" data-path=\"assets/faa/practice_test/figure_25/main-57bc6a20997504c7dfe6d1e894e7811561453c502faadd4248a5f29a8ea0c65e.png\">Figure 25</a></li>\n";
print "                  <li role=\"presentation\"><a href=\"#\" data-toggle=\"modal\" data-target=\"#faa_modal\" data-path=\"assets/faa/practice_test/sectional_legend-cb94b2493a47391b96791f85a9e4b6f365b14707eef1858412d46b2422fba0b0.png\">Sectional Legend</a></li>\n";
print "              </ul>\n";
print "              <div class=\"radio\">\n";
print "                <label>\n";
print "                  <input type=\"radio\" name=\"question_1\" id=\"question_1_answer_0\" value=\"false\">\n";
print "                  700 feet AGL\n";
print "                </label>\n";
print "              </div>\n";
print "              <div class=\"radio\">\n";
print "                <label>\n";
print "                  <input type=\"radio\" name=\"question_1\" id=\"question_1_answer_1\" value=\"true\">\n";
print "                  2,900 feet MSL\n";
print "                </label>\n";
print "              </div>\n";
print "              <div class=\"radio\">\n";
print "                <label>\n";
print "                  <input type=\"radio\" name=\"question_1\" id=\"question_1_answer_2\" value=\"false\">\n";
print "                  2,500 feet MSL\n";
print "                </label>\n";
print "              </div>\n";
print "          </div>\n";
print "          <hr>\n";
print "          <div class=\"form-group question\">\n";
print "            <h3>To avoid a possible collision with a manned airplane, you estimate that your small UA climbed to an altitude greater than 600 feet AGL. To whom must you report the deviation?</h3>\n";
print "              <div class=\"radio\">\n";
print "                <label>\n";
print "                  <input type=\"radio\" name=\"question_2\" id=\"question_2_answer_0\" value=\"false\">\n";
print "                  The National Transportation Safety Board.\n";
print "                </label>\n";
print "              </div>\n";
print "              <div class=\"radio\">\n";
print "                <label>\n";
print "                  <input type=\"radio\" name=\"question_2\" id=\"question_2_answer_1\" value=\"false\">\n";
print "                  Air Traffic Control.\n";
print "                </label>\n";
print "              </div>\n";
print "              <div class=\"radio\">\n";
print "                <label>\n";
print "                  <input type=\"radio\" name=\"question_2\" id=\"question_2_answer_2\" value=\"true\">\n";
print "                  The FAA, upon request.\n";
print "                </label>\n";
print "              </div>\n";
print "          </div>\n";
print "          <hr>\n";
print "          <div class=\"form-group question\">\n";
print "            <h3>According to 14 CFR part 107, what is required to operate a small UA within 30 minutes after official sunset?</h3>\n";
print "              <div class=\"radio\">\n";
print "                <label>\n";
print "                  <input type=\"radio\" name=\"question_3\" id=\"question_3_answer_0\" value=\"true\">\n";
print "                  Use of anti-collision lights.\n";
print "                </label>\n";
print "              </div>\n";
print "              <div class=\"radio\">\n";
print "                <label>\n";
print "                  <input type=\"radio\" name=\"question_3\" id=\"question_3_answer_1\" value=\"false\">\n";
print "                  Use of a transponder.\n";
print "                </label>\n";
print "              </div>\n";
print "              <div class=\"radio\">\n";
print "                <label>\n";
print "                  <input type=\"radio\" name=\"question_3\" id=\"question_3_answer_2\" value=\"false\">\n";
print "                  Must be operated in a rural area.\n";
print "                </label>\n";
print "              </div>\n";
print "          </div>\n";
print "          <hr>\n";
print "          <div class=\"form-group question\">\n";
print "            <h3>(Refer to Figure 20.) Who would a Remote Pilot in Command contact to 'CHECK NOTAMS' as it is noted in the CAUTION box regarding the unmarked balloon?</h3>\n";
print "              <ul class=\"nav nav-pills\">\n";
print "                  <li role=\"presentation\"><a href=\"#\" data-toggle=\"modal\" data-target=\"#faa_modal\" data-path=\"assets/faa/practice_test/figure_20/main-7bb39947fef2e22d315ec0cc555cad991fa39b6782cfd7875796894340f3ae68.png\">Figure 20</a></li>\n";
print "                  <li role=\"presentation\"><a href=\"#\" data-toggle=\"modal\" data-target=\"#faa_modal\" data-path=\"assets/faa/practice_test/sectional_legend-cb94b2493a47391b96791f85a9e4b6f365b14707eef1858412d46b2422fba0b0.png\">Sectional Legend</a></li>\n";
print "              </ul>\n";
print "              <div class=\"radio\">\n";
print "                <label>\n";
print "                  <input type=\"radio\" name=\"question_4\" id=\"question_4_answer_0\" value=\"true\">\n";
print "                  Flight Service\n";
print "                </label>\n";
print "              </div>\n";
print "              <div class=\"radio\">\n";
print "                <label>\n";
print "                  <input type=\"radio\" name=\"question_4\" id=\"question_4_answer_1\" value=\"false\">\n";
print "                  NTSB office\n";
print "                </label>\n";
print "              </div>\n";
print "              <div class=\"radio\">\n";
print "                <label>\n";
print "                  <input type=\"radio\" name=\"question_4\" id=\"question_4_answer_2\" value=\"false\">\n";
print "                  FAA district office\n";
print "                </label>\n";
print "              </div>\n";
print "          </div>\n";
print "          </ul>\n";
print "        <div class=\"row\">\n";
print "          <div class=\"col-sm-8 col-sm-offset-2\">\n";
print "            <button type=\"submit\" id=\"faa_submit\" class=\"btn btn-primary btn-lg btn-block\">Grade</button>\n";
print "          </div>\n";
print "        </div>\n";
print "        \n";
print "      </form>\n";
print "     </div>\n";
print "   \n";
print "  \n";
print "    </div>\n";
print "   </div>\n";
print "  </div>\n";
print " </div>\n";
print "\n";
print "\n";
print "<footer class=\"container-fluid text-center\">\n";
print "  <div class=\"container\">\n";
print "    <div class=\"copyright\">\n";
print "      © 2017 <a href=\"http://www.redcatpropware.com/\">RedCat PropWare</a>. All Rights Reserved.\n";
print "    </div>\n";
print "    <div class=\"footer-links\">\n";
print "          <a href=\"http://www.redcatpropware.com/privacy-policy\">Privacy Policy</a>\n";
print "    <a href=\"http://www.redcatpropware.com/disclaimer\">Disclaimer</a>\n";
print "    </div>\n";
print "  </div>\n";
print "</footer>\n";
print "\n";
print "</body>\n";
print "</html>\n";

?>
